# Generated by Django 4.0.3 on 2022-04-27 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fotos', '0005_foto_dislikes_foto_likes_foto_users_reaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='foto',
            name='users_reaction',
        ),
        migrations.RemoveField(
            model_name='foto',
            name='likes',
        ),
        migrations.AddField(
            model_name='foto',
            name='likes',
            field=models.ManyToManyField(related_name='fotos_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
