# Generated by Django 4.0.3 on 2022-04-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0007_foto_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foto',
            options={'ordering': ('created_date',)},
        ),
    ]
