# Generated by Django 4.0.3 on 2022-04-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0008_alter_foto_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='author',
            new_name='autor',
        ),
    ]
