# Generated by Django 4.0.3 on 2022-04-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0009_rename_author_foto_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='about',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='profile_img',
            field=models.ImageField(blank=True, default='/stock/default.jpg', null=True, upload_to=''),
        ),
    ]
