# Generated by Django 4.0.3 on 2022-04-30 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0017_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilizador',
            options={'permissions': [('criar_post', 'Pode criar posts'), ('criar_like_dislike', 'Pode dar likes ou dislikes'), ('criar_comentario', 'Pode criar comentários')]},
        ),
    ]
