# Generated by Django 4.0.3 on 2022-05-02 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fotos', '0018_alter_utilizador_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='likes',
            field=models.ManyToManyField(related_name='comentarios_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
