# Generated by Django 4.0.3 on 2022-05-02 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fotos', '0019_comentario_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='likes',
        ),
        migrations.AddField(
            model_name='comentario',
            name='votos',
            field=models.ManyToManyField(related_name='comentarios_votos', to=settings.AUTH_USER_MODEL),
        ),
    ]
