# Generated by Django 4.0.3 on 2022-05-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0020_remove_comentario_likes_comentario_votos'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='background_img',
            field=models.ImageField(blank=True, upload_to='profile/background'),
        ),
    ]
