# Generated by Django 4.0.3 on 2022-05-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0023_alter_utilizador_background_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='background_img',
        ),
    ]
