# Generated by Django 4.0.3 on 2022-05-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0024_remove_utilizador_background_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='votos',
        ),
    ]
