# Generated by Django 4.0.3 on 2022-05-06 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fotos', '0025_remove_comentario_votos'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='followers',
            field=models.ManyToManyField(related_name='utilizador_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='following',
            field=models.ManyToManyField(related_name='utilizador_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
