# Generated by Django 4.0.3 on 2022-05-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0027_comentario_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilizador',
            options={'permissions': [('criar_post', 'Pode criar posts'), ('criar_like_dislike', 'Pode dar likes ou dislikes'), ('criar_comentario', 'Pode criar comentários'), ('dar_follow', 'Pode dar follow a outro utilizador')]},
        ),
    ]
